### ISSUE TITLE
[ISSUE] NPC with auto-rolled, highest initiative doesn't go first in combat tracker

### ISSUE THREAD

**Issue by weepingminotaur** [veevelder/quick-combat#38]
If the Fast/Prompt option is on, an NPC with auto-rolled initiative who has the highest initiative of all combatants will not go first when the encounter begins. The combat tracker seems to default to the PC with the highest initiative.

**Comment by veevelder** [comment]
yeah i've noticed this issue, and have been trying to figure something out. It might take me a bit just letting you know

**Comment by veevelder** [comment]
I do believe I have fixed the issue, can you let me know if the newest version works for you?

**Comment by weepingminotaur** [comment]
Just updated and tested, still doesn't work. See attached screenshot. PC is the highlighted combatant upon entering combat even though the monster has higher inish.
<img width="385" alt="Screenshot 2023-09-17 at 12 51 10 PM" src="https://github.com/veevelder/quick-combat/assets/90105219/2647f29d-867c-41b4-bd15-a9188ae18408">

**Comment by veevelder** [comment]
what versions of stuff are you using?

**Comment by weepingminotaur** [comment]
Latest versions of everything: Quick Combat 0.5.4, Pf2e system 5.5.2, Foundry v11 build 308

**Comment by Mitthraw** [comment]
Hi, first of all thanks for this great module. I also have this issue. Each time I start a fight, the second combattant in initiative order is highlighted.

**Comment by veevelder** [comment]
Apologies for taking some time but I finally have some time to work on this.

I can't seem to replicate this issue, could either or both @Mitthraw and @weepingminotaur give me the debug output of you starting combat. (Hit F12 find the console and copy/paste the output). Also give me your Quick Combat Settings and a list of other modules you are using so I can see if there is a conflict somewhere.

**Comment by Mitthraw** [comment]
Hi,

Please find below the console output. The visible error happens when tokens are added to the combat (before the start of the fight) and seems to be directly related to foundry (as there is an opened issue about it). Don't know if it is related.

![image](https://github.com/veevelder/quick-combat/assets/77486604/06869135-7456-489d-90b0-79990eab7792)
![image](https://github.com/veevelder/quick-combat/assets/77486604/a5d0e8dd-481f-4d0f-b612-ce108047bf0f)

Here's the list of active modules in the game

![image](https://github.com/veevelder/quick-combat/assets/77486604/6757bf76-c697-4824-b521-dd4740c85e65)

And here's the Quick Combat Settings

![image](https://github.com/veevelder/quick-combat/assets/77486604/617fcf63-b4de-4696-a4a6-933d649de906)
![image](https://github.com/veevelder/quick-combat/assets/77486604/1d9566ba-918c-4441-ba64-1a3f9adabd50)

**Comment by veevelder** [comment]
so hopefully this time it should be fixed, the previous attempt only worked when using the hot key (my default method) and not using the token toggle combatant buttons.

**Comment by Mitthraw** [comment]
Yes, it is fixed :) Thanks !
